
seller:
  userName: seller
  password: relles

buyer:
  userName: buyer
  password: reyub


web:
  upload-path: /imgs/ #自定义文件上传路径

multipart:
  maxRequestSize: 200Mb #设置所有文件最大内存
  maxFileSize: 10Mb #设置单个文件最大内存

#热部署生效
spring.devtools.restart.enabled: false
#设置重启的目录
spring.devtools.restart.additional-paths: src/main/java

#数据库配置
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/content-sale?useUnicode=true&characterEncoding=utf8
    username: root
    password: 123
  #配置自动建表：updata:没有表新建，有表更新操作,控制台显示建表语句
  jpa:
    hibernate:
      ddl-auto: update
#    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG

#后端服务的地址
service_address: http://localhost:8080/imgs/